var carCitys= new Array();

carCitys.push(['CGQ','长春','CHANGCHUN','CC']); 
carCitys.push(['CKG','重庆','CHONGQING','CQ']); 
carCitys.push(['CSX','长沙','CHANGSHA','CC']); 
carCitys.push(['CTU','成都','CHENGDU','CD']); 
carCitys.push(['CZX','常州','CHANGZHOU','CZ']); 
carCitys.push(['DLC','大连','DALIAN','DL']); 
carCitys.push(['FOC','福州','FUZHOU','FZ']); 
carCitys.push(['FOH','佛山','FOSHAN','FS']); 
carCitys.push(['PEK','北京','BEIJING','BJ']); 
carCitys.push(['DNG','东莞','DONGGUAN','DG']); 
carCitys.push(['CAN','广州','GUANGZHOU','GZ']); 
carCitys.push(['HAK','海口','HAIKOU','HK']); 
carCitys.push(['HFE','合肥','HEFEI','HF']); 
carCitys.push(['HGH','杭州','HANGZHOU','HZ']); 
carCitys.push(['KWL','桂林','GUILIN','GL']); 
carCitys.push(['TNA','济南','JINAN','JN']); 
carCitys.push(['KHN','南昌','NANCHANG','NC']); 
carCitys.push(['KMG','昆明','KUNMING','KM']); 
carCitys.push(['NGB','宁波','NINGBO','NB']); 
carCitys.push(['NKG','南京','NANJING','NJ']); 
carCitys.push(['NTG','南通','NANTONG','NT']); 
carCitys.push(['KUS','昆山','KUNSHAN','KS']); 
carCitys.push(['SHA','上海','SHANGHAI','SH']); 
carCitys.push(['SHE','沈阳','SHENYANG','SY']); 
carCitys.push(['SYX','三亚','SANYA','SY']); 
carCitys.push(['SZX','深圳','SHENZHEN','SZ']); 
carCitys.push(['TAO','青岛','QINGDAO','QD']); 
carCitys.push(['TSN','天津','TIANJIN','TJ']); 
carCitys.push(['TYN','太原','TAIYUAN','TY']); 
carCitys.push(['WUH','武汉','WUHAN','WH']); 
carCitys.push(['WUX','无锡','WUXI','WX']); 
carCitys.push(['SDE','顺德','SHUNDE','SD']); 
carCitys.push(['SOZ','苏州','SUZHOU','SZ']); 
carCitys.push(['CGO','郑州','ZHENGZHOU','ZZ']); 
carCitys.push(['XIA','西安','XIAN','XA']); 
carCitys.push(['XMN','厦门','XIAMEN','XM']); 
carCitys.push(['QDH','千岛湖','QIANDAOHU','QDH']); 
carCitys.push(['ZUH','珠海','ZHUHAI','ZH']); 



var carHotCitys= new Array();

carHotCitys.push(['PEK','北京','BEIJING','BJ']); 
carHotCitys.push(['SHA','上海','SHANGHAI','SH']); 
carHotCitys.push(['CAN','广州','GUANGZHOU','GZ']); 
carHotCitys.push(['SZX','深圳','SHENZHEN','SZ']); 
carHotCitys.push(['CTU','成都','CHENGDU','CD']); 
carHotCitys.push(['HGH','杭州','HANGZHOU','HZ']); 
carHotCitys.push(['WUH','武汉','WUHAN','WH']); 
carHotCitys.push(['SOZ','苏州','SUZHOU','SZ']); 
carHotCitys.push(['CSX','长沙','CHANGSHA','CC']); 
carHotCitys.push(['NKG','南京','NANJING','NJ']); 
carHotCitys.push(['NGB','宁波','NINGBO','NB']); 
carHotCitys.push(['TSN','天津','TIANJIN','TJ']); 


var carPinYinCitys= new Array();

carPinYinCitys.push(['A-F','CGQ','长春']); 
carPinYinCitys.push(['A-F','CKG','重庆']); 
carPinYinCitys.push(['A-F','CSX','长沙']); 
carPinYinCitys.push(['A-F','CTU','成都']); 
carPinYinCitys.push(['A-F','CZX','常州']); 
carPinYinCitys.push(['A-F','DLC','大连']); 
carPinYinCitys.push(['A-F','FOC','福州']); 
carPinYinCitys.push(['A-F','FOH','佛山']); 
carPinYinCitys.push(['A-F','PEK','北京']); 
carPinYinCitys.push(['A-F','DNG','东莞']); 
carPinYinCitys.push(['G-J','CAN','广州']); 
carPinYinCitys.push(['G-J','HAK','海口']); 
carPinYinCitys.push(['G-J','HFE','合肥']); 
carPinYinCitys.push(['G-J','HGH','杭州']); 
carPinYinCitys.push(['G-J','KWL','桂林']); 
carPinYinCitys.push(['G-J','TNA','济南']); 
carPinYinCitys.push(['K-N','KHN','南昌']); 
carPinYinCitys.push(['K-N','KMG','昆明']); 
carPinYinCitys.push(['K-N','NGB','宁波']); 
carPinYinCitys.push(['K-N','NKG','南京']); 
carPinYinCitys.push(['K-N','NTG','南通']); 
carPinYinCitys.push(['K-N','KUS','昆山']); 
carPinYinCitys.push(['P-W','SHA','上海']); 
carPinYinCitys.push(['P-W','SHE','沈阳']); 
carPinYinCitys.push(['P-W','SYX','三亚']); 
carPinYinCitys.push(['P-W','SZX','深圳']); 
carPinYinCitys.push(['P-W','TAO','青岛']); 
carPinYinCitys.push(['P-W','TSN','天津']); 
carPinYinCitys.push(['P-W','TYN','太原']); 
carPinYinCitys.push(['P-W','WUH','武汉']); 
carPinYinCitys.push(['P-W','WUX','无锡']); 
carPinYinCitys.push(['P-W','SDE','顺德']); 
carPinYinCitys.push(['P-W','SOZ','苏州']); 
carPinYinCitys.push(['P-W','QDH','千岛湖']); 
carPinYinCitys.push(['X-Z','CGO','郑州']); 
carPinYinCitys.push(['X-Z','XIA','西安']); 
carPinYinCitys.push(['X-Z','XMN','厦门']); 
carPinYinCitys.push(['X-Z','ZUH','珠海']); 
