/** 机票常用城市 */
var commoncitysFlight=[];
commoncitysFlight.push(['PEK','北京','BEIJING','BJ']);
commoncitysFlight.push(['SHA','上海','SHANGHAI','SH']);
commoncitysFlight.push(['CAN','广州','GUANGZHOU','GZ']);
commoncitysFlight.push(['SZX','深圳','SHENZHEN','SZ']);
commoncitysFlight.push(['CTU','成都','CHENGDU','CD']);
commoncitysFlight.push(['HGH','杭州','HANGZHOU','HZ']);
commoncitysFlight.push(['CSX','长沙','CHANGSHA','CS']);
commoncitysFlight.push(['CKG','重庆','CHONGQING','CQ']);
commoncitysFlight.push(['KMG','昆明','KUNMING','KM']);
commoncitysFlight.push(['XIY','西安','XIAN','XA']);
commoncitysFlight.push(['WUH','武汉','WUHAN','WH']);
commoncitysFlight.push(['NKG','南京','NANJING','NJ']);
commoncitysFlight.push(['TAO','青岛','QINGDAO','QD']);
commoncitysFlight.push(['SYX','三亚','SANYA','SY']);
commoncitysFlight.push(['XMN','厦门','XIAMEN','XM']);

/** 机票所有城市 */
var citysForFlight=[];
citysForFlight.push(['SHA','上海','SHANGHAI','SH']);
citysForFlight.push(['HYN','黄岩(台州)','HUANGYAN','HY']);
citysForFlight.push(['HGH','杭州','HANGZHOU','HZ']);
citysForFlight.push(['YIW','义乌','YIWU','YW']);
citysForFlight.push(['JUZ','衢州','JUZHOU','QZ']);
citysForFlight.push(['HSN','舟山(普陀山)','ZHOUSHAN','ZS']);
citysForFlight.push(['WNZ','温州','WENZHOU','WZ']);
citysForFlight.push(['NGB','宁波','NINGBO','NB']);
citysForFlight.push(['WNH','文山壮族苗族自治州','PUZHEHE','']);
citysForFlight.push(['LNJ','临沧','LINCANG','LC']);
citysForFlight.push(['ZAT','昭通','ZHAOTONG','ZT']);
citysForFlight.push(['SYM','思茅','SIMAO','SM']);
citysForFlight.push(['LUM','芒市','MANSHI','MS']);
citysForFlight.push(['BSD','保山','BAOSHAN','BS']);
citysForFlight.push(['KMG','昆明','KUNMING','KM']);
citysForFlight.push(['JHG','西双版纳','XISHUANGBANNA','XSBN']);
citysForFlight.push(['DLU','大理','DALI','DL']);
citysForFlight.push(['TCZ','腾冲','TENGCHONG','']);
citysForFlight.push(['DIG','迪庆','DIQING','DQ']);
citysForFlight.push(['LJG','丽江','LIJIANG','LJ']);
citysForFlight.push(['BPX','昌都地区','BANGDA','']);
citysForFlight.push(['LXA','拉萨','LASA','LS']);
citysForFlight.push(['LZY','林芝','LINZHI','']);
citysForFlight.push(['NLT','新源','XINYUAN','']);
citysForFlight.push(['TCG','塔城','TACHENG','TC']);
citysForFlight.push(['IQM','且末','QIEMO','QM']);
citysForFlight.push(['KCA','库车','KUCHE','KC']);
citysForFlight.push(['HTN','和田','HETAN','HT']);
citysForFlight.push(['HMI','哈密','HAMI','HM']);
citysForFlight.push(['FYN','富蕴','FUYUN','FY']);
citysForFlight.push(['AKU','阿克苏','AGESU','AKS']);
citysForFlight.push(['URC','乌鲁木齐','WULUMUQI','WLMQ']);
citysForFlight.push(['KHG','喀什','KASHI','KS']);
citysForFlight.push(['KRL','库尔勒','KUERLE','KEL']);
citysForFlight.push(['KRY','克拉玛依','KELAMAYI','KLMY']);
citysForFlight.push(['AAT','阿勒泰','ALETAI','ALT']);
citysForFlight.push(['YIN','伊宁','YINING','YN']);
citysForFlight.push(['TSN','天津','TIANJIN','TJ']);
citysForFlight.push(['AKA','安康','ANKANG','AK']);
citysForFlight.push(['ENY','延安','YANAN','YA']);
citysForFlight.push(['HZG','汉中','HANZHONG','HZ']);
citysForFlight.push(['XIY','西安','XIAN','XA']);
citysForFlight.push(['UYN','榆林','YULIN','YL']);
citysForFlight.push(['CIH','长治','CHANGZHI','CZ']);
citysForFlight.push(['TYN','太原','TAIYUAN','TY']);
citysForFlight.push(['DAT','大同','DATONG','DT']);
citysForFlight.push(['YCU','运城','YUNCHENG','YC']);
citysForFlight.push(['TNA','济南','JINAN','JN']);
citysForFlight.push(['YNT','烟台','YANTAI','YT']);
citysForFlight.push(['JNG','济宁','JINING','JL']);
citysForFlight.push(['DOY','东营','DONGYING','DY']);
citysForFlight.push(['LYI','临沂','LINYI','LY']);
citysForFlight.push(['WEF','潍坊','WEIFANG','WF']);
citysForFlight.push(['TAO','青岛','QINGDAO','QD']);
citysForFlight.push(['WEH','威海','WEIHAI','WH']);
citysForFlight.push(['KGT','康定','KANGDING','']);
citysForFlight.push(['GHN','广汉','GUANGHAN','GH']);
citysForFlight.push(['DAX','达县','DAXIAN','DX']);
citysForFlight.push(['CTU','成都','CHENGDU','CD']);
citysForFlight.push(['MIG','绵阳','MIANYANG','MY']);
citysForFlight.push(['YBP','宜宾','YIBIN','YB']);
citysForFlight.push(['LZO','泸州','LUZHOU','LZ']);
citysForFlight.push(['GYS','广元','GUANGYUAN','']);
citysForFlight.push(['XIC','西昌','XICHANG','XC']);
citysForFlight.push(['NAO','南充','NANCHONG','NC']);
citysForFlight.push(['PZI','攀枝花','PANZHIHUA','PZH']);
citysForFlight.push(['YUS','玉树','YUSHU','YS']);
citysForFlight.push(['GOQ','格尔木','GELANMU','GEM']);
citysForFlight.push(['XNN','西宁','XINING','XN']);
citysForFlight.push(['ZHY','中卫','ZHONGWEI','']);
citysForFlight.push(['INC','银川','YINCHUAN','YC']);
citysForFlight.push(['XIL','锡林浩特','XILINHAOTE','XLHT']);
citysForFlight.push(['HLH','乌兰浩特','WULANHAOTE','WLHT']);
citysForFlight.push(['WUA','乌海','WUHAI','WH']);
citysForFlight.push(['TGO','通辽','TONGLIAO','TL']);
citysForFlight.push(['HET','呼和浩特','HUHEHAOTE','HHHT']);
citysForFlight.push(['DSN','鄂尔多斯','EERDUOSI','EEDS']);
citysForFlight.push(['NZH','满洲里','MANZHOULI','MZL']);
citysForFlight.push(['HLD','海拉尔','HAILAER','HLE']);
citysForFlight.push(['CIF','赤峰','CHIFENG','CF']);
citysForFlight.push(['BAV','包头','BAOTOU','BT']);
citysForFlight.push(['CHG','朝阳','CHAOYANG','CY']);
citysForFlight.push(['SHE','沈阳','SHENYANG','SY']);
citysForFlight.push(['DLC','大连','DALIAN','DL']);
citysForFlight.push(['DDG','丹东','DANDONG','DD']);
citysForFlight.push(['JNZ','锦州','JINZHOU','JZ']);
citysForFlight.push(['AOG','鞍山','ANSHAN','AS']);
citysForFlight.push(['KHN','南昌','NANCHANG','NC']);
citysForFlight.push(['JDZ','景德镇','JINDEZHEN','JDZ']);
citysForFlight.push(['JIU','九江','JIUJIANG','JJ']);
citysForFlight.push(['KOW','赣州','GANZHOU','GZ']);
citysForFlight.push(['','抚州','','']);
citysForFlight.push(['JGS','井冈山','JINGGANGSHAN','JGS']);
citysForFlight.push(['KNC','吉安','JIAN','JA']);
citysForFlight.push(['LYG','连云港','LIANYUNGANG','LYG']);
citysForFlight.push(['SZV','苏州','SUZHOU','SZ']);
citysForFlight.push(['YNZ','盐城','YANCHENG','YC']);
citysForFlight.push(['XUZ','徐州','XUZHOU','XZ']);
citysForFlight.push(['NKG','南京','NANJING','NJ']);
citysForFlight.push(['NTG','南通','NANTONG','NT']);
citysForFlight.push(['CZX','常州','CHANGZHOU','CZ']);
citysForFlight.push(['WUX','无锡','WUXI','WX']);
citysForFlight.push(['NBS','白山','CHANGBAISHAN','']);
citysForFlight.push(['TNH','通化','TONGHUA','TH']);
citysForFlight.push(['JIL','吉林','JILIN','JL']);
citysForFlight.push(['CGQ','长春','CHANGCHUN','CC']);
citysForFlight.push(['YNJ','延吉','YANJI','YJ']);
citysForFlight.push(['HJJ','怀化','HUAIHUA','HH']);
citysForFlight.push(['DYG','张家界','ZHANGJIAJIE','ZJJ']);
citysForFlight.push(['CGD','常德','CHANGDE','CD']);
citysForFlight.push(['LLF','永州','LINGLING','']);
citysForFlight.push(['CSX','长沙','CHANGSHA','CS']);
citysForFlight.push(['HNY','衡阳','HENGYANG','HY']);
citysForFlight.push(['LDS','伊春','YICHUN','YC']);
citysForFlight.push(['JXA','鸡西','JIXI','JX']);
citysForFlight.push(['OHE','漠河','MOHE','MH']);
citysForFlight.push(['HRB','哈尔滨','HAERBIN','HRB']);
citysForFlight.push(['HEK','黑河','HEIHE','HH']);
citysForFlight.push(['NDG','齐齐哈尔','QIQIHAER','QQHE']);
citysForFlight.push(['JMU','佳木斯','JIAMUSI','JMS']);
citysForFlight.push(['DQA','大庆','DAQING','DQ']);
citysForFlight.push(['MDG','牡丹江','MUDANJIANG','MDJ']);
citysForFlight.push(['LYA','洛阳','LUOYANG','LY']);
citysForFlight.push(['NNY','南阳','NANYANG','NY']);
citysForFlight.push(['CGO','郑州','ZHENGZHOU','ZZ']);
citysForFlight.push(['SJW','石家庄','SHIJIAZHUANG','SJZ']);
citysForFlight.push(['SHP','秦皇岛','QINHUANGDAO','QHD']);
citysForFlight.push(['HDG','邯郸','HANDAN','HD']);
citysForFlight.push(['SHS','沙市','SHASHI','SS']);
citysForFlight.push(['WUH','武汉','WUHAN','WH']);
citysForFlight.push(['XFN','襄阳','XIANGYANG','XY']);
citysForFlight.push(['ENH','恩施','ENSHI','ES']);
citysForFlight.push(['YIH','宜昌','YICHANG','YC']);
citysForFlight.push(['HAK','海口','HAIKOU','HK']);
citysForFlight.push(['SYX','三亚','SANYA','SY']);
citysForFlight.push(['LLB','荔波','LIBO','LB']);
citysForFlight.push(['XYI','兴义','XINGYI','XY']);
citysForFlight.push(['KWE','贵阳','GUIYANG','GY']);
citysForFlight.push(['TEN','铜仁','TONGREN','TR']);
citysForFlight.push(['ZYI','遵义','ZUNYI','ZY']);
citysForFlight.push(['BHY','北海','BEIHAI','BH']);
citysForFlight.push(['KWL','桂林','GUILIN','GL']);
citysForFlight.push(['LZH','柳州','LIUZHOU','LZ']);
citysForFlight.push(['NNG','南宁','NANNING','NN']);
citysForFlight.push(['BAS','百色','BAISE','BS']);
citysForFlight.push(['WUZ','梧州','WUZHOU','WZ']);
citysForFlight.push(['THQ','天水','TIANSHUI','']);
citysForFlight.push(['IQN','庆阳','QINGYANG','QY']);
citysForFlight.push(['CHW','酒泉','JIUQUAN','JQ']);
citysForFlight.push(['JGN','嘉峪关','JIAYUGUAN','JYG']);
citysForFlight.push(['DNH','敦煌','DUNHUANG','DH']);
citysForFlight.push(['LHW','兰州','LANZHOU','LZ']);
citysForFlight.push(['ZHA','湛江','ZHANJIANG','ZJ']);
citysForFlight.push(['MXZ','梅州','MEIZHOU','MZ']);
citysForFlight.push(['ZUH','珠海','ZHUHAI','ZH']);
citysForFlight.push(['FUO','佛山','FOSHAN','FS']);
citysForFlight.push(['SWA','汕头','SHANTOU','ST']);
citysForFlight.push(['SZX','深圳','SHENZHEN','SZ']);
citysForFlight.push(['CAN','广州','GUANGZHOU','GZ']);
citysForFlight.push(['XMN','厦门','XIAMEN','XM']);
citysForFlight.push(['WUS','武夷山','WUYISHAN','WYS']);
citysForFlight.push(['QHU','泉州','QUANZHOU','QZ']);
citysForFlight.push(['LIC','连城','LIANCHENG','LC']);
citysForFlight.push(['JJN','晋江','JINJIANG','JJ']);
citysForFlight.push(['FOC','福州','FUZHOU','FZ']);
citysForFlight.push(['WXN','万县','WANXIAN','WX']);
citysForFlight.push(['CKG','重庆','CHONGQING','CQ']);
citysForFlight.push(['TXN','黄山','HUANGSHAN','HS']);
citysForFlight.push(['BFU','蚌埠','BENGBU','BB']);
citysForFlight.push(['FUG','阜阳','FUYANG','FY']);
citysForFlight.push(['HFE','合肥','HEFEI','HF']);
citysForFlight.push(['AQG','安庆','ANQING','AQ']);
citysForFlight.push(['PEK','北京','BEIJING','BJ']);
citysForFlight.push(['HKG','香港','XIANGGANG','XG']);
citysForFlight.push(['MAC','澳门','AOMEN','AM']);
citysForFlight.push(['HKG','香港','HONGKONG','HK']);
citysForFlight.push(['JZH','九寨沟','JIUZHAIGOU','JZG']);
citysForFlight.push(['KJI','喀纳斯','KANASI','KNS']);
citysForFlight.push(['TINS','天水','TIANSHUI','TS']);
citysForFlight.push(['TVS','唐山','TANGSHAN','TS']);

/** 酒店常用城市 */
var commoncitysHotel = new Array();
commoncitysHotel.push(['PEK','北京','BEIJING','BJ']);
commoncitysHotel.push(['SHA','上海','SHANGHAI','SH']);
commoncitysHotel.push(['CAN','广州','GUANGZHOU','GZ']);
commoncitysHotel.push(['SZX','深圳','SHENZHEN','SZ']);
commoncitysHotel.push(['CTU','成都','CHENGDU','CD']);
commoncitysHotel.push(['HGH','杭州','HANGZHOU','HZ']);
commoncitysHotel.push(['CSX','长沙','CHANGSHA','CS']);
commoncitysHotel.push(['CKG','重庆','CHONGQING','CQ']);
commoncitysHotel.push(['KMG','昆明','KUNMING','KM']);
commoncitysHotel.push(['XIA','西安','XIAN','XA']);
commoncitysHotel.push(['WUH','武汉','WUHAN','WH']);
commoncitysHotel.push(['NKG','南京','NANJING','NJ']);
commoncitysHotel.push(['TAO','青岛','QINGDAO','QD']);
commoncitysHotel.push(['SYX','三亚','SANYA','SY']);
commoncitysHotel.push(['XMN','厦门','XIAMEN','XM']);
commoncitysHotel.push(['HKG','香港','HONGKONG','XG']);
commoncitysHotel.push(['MAC','澳门','MACAU','AM']);

/** 酒店所有城市 */
var citysForHotel=new Array();
	citysForHotel[0]=new Array('AKU','阿克苏','AKESU','AKS');
	citysForHotel[1]=new Array('ALT','阿勒泰','ALETAI','ALT');
	citysForHotel[2]=new Array('BAO','博鳌','BOAO','BA');
	citysForHotel[3]=new Array('BAS','百色','BAISE','BS');
	citysForHotel[4]=new Array('BEJ','布尔津','BUERJIN ','BEJ');
	citysForHotel[5]=new Array('BHY','北海','BEIHAI','BH');
	citysForHotel[6]=new Array('BSD','保山','BAOSHAN','BS');
	citysForHotel[7]=new Array('CHD','常德','CHANGDE','CD');
	citysForHotel[8]=new Array('CHW','酒泉','JIUQUAN','JQ');
	citysForHotel[9]=new Array('CKG','重庆','CHONGQING','CQ');
	citysForHotel[10]=new Array('CSX','长沙','CHANGSHA','CS');
	citysForHotel[11]=new Array('CTU','成都','CHENGDU','CD');
	citysForHotel[12]=new Array('CUX','楚雄','CHUXIONG','CX');
	citysForHotel[13]=new Array('DAZ','儋州','DANZHOU','DZ');
	citysForHotel[14]=new Array('DIA','定安县','ANDINGXIAN','ADX');
	citysForHotel[15]=new Array('DJY','都江堰','DUJIANGYAN','DJY');
	citysForHotel[16]=new Array('DNG','东莞','DONGGUAN','DG');
	citysForHotel[17]=new Array('DNH','敦煌','DUNHUANG','DH');
	citysForHotel[18]=new Array('DOA','东方','DONGFANG','DF');
	citysForHotel[19]=new Array('DQ','迪庆','DIQING','DQ');
	citysForHotel[20]=new Array('EMS','峨眉山','EMEISHAN','EMS');
	citysForHotel[21]=new Array('ENS','恩施','ENSHI','ES');
	citysForHotel[22]=new Array('FHX','凤凰县','FENGHUANGXIAN','FHX');
	citysForHotel[23]=new Array('GHN','广汉','GUANGHAN','GH');
	citysForHotel[24]=new Array('GOQ','格尔木','GEERMU','GEM');
	citysForHotel[25]=new Array('GUA','广安','GUANGAN','GA');
	citysForHotel[26]=new Array('GUY','广元','GUANGYUAN','GY');
	citysForHotel[27]=new Array('HAK','海口','HAIKOU','HK');
	citysForHotel[28]=new Array('HCH','河池','HECHI','HC');
	citysForHotel[29]=new Array('HHU','怀化','HUAIHUA','HH');
	citysForHotel[30]=new Array('HJJ','芷江','ZHIJIANG','ZJ');
	citysForHotel[31]=new Array('HLG','海螺沟','HAILUOGOU','HLG');
	citysForHotel[32]=new Array('HMI','哈密','HAMI','HM');
	citysForHotel[33]=new Array('IQM','且末','QIEMO','QM');
	citysForHotel[34]=new Array('IQN','庆阳','QINGYANG','QY');
	citysForHotel[35]=new Array('JGN','嘉峪关','JIAYUGUAN','JYG');
	citysForHotel[36]=new Array('JIQ','江油','JIANGYOU','JY');
	citysForHotel[37]=new Array('JZG','九寨沟','JIUZHAIGOU','JZG');
	citysForHotel[38]=new Array('JZH','荆州','JINGZHOU','JZ');
	citysForHotel[39]=new Array('KAS','喀什','KASHI','KS');
	citysForHotel[40]=new Array('KCA','库车','KUCHE','KC');
	citysForHotel[41]=new Array('KEL','库尔勒','KUERLE','KEL');
	citysForHotel[42]=new Array('KLM','克拉玛依','KELAMAYI','KLMY');
	citysForHotel[43]=new Array('KNS','喀纳斯','KANASI','KNS');
	citysForHotel[44]=new Array('KWE','贵阳','GUIYANG','GY');
	citysForHotel[45]=new Array('KYN','开元','KAIYUAN','KY');
	citysForHotel[46]=new Array('LJG','丽江','LIJIANG','LJ');
	citysForHotel[47]=new Array('LOD','娄底','LOUDI','LD');
	citysForHotel[48]=new Array('LSA','拉萨','LASHA','LS');
	citysForHotel[49]=new Array('LSN','乐山','LESHAN','LS');
	citysForHotel[50]=new Array('MAC','澳门','AOMEN','AM');
	citysForHotel[51]=new Array('NAC','南充','NANCHONG','NC');
	citysForHotel[52]=new Array('NEJ','内江','NEIJIANG','NJ');
	citysForHotel[53]=new Array('QIH','琼海','QINGHAI','QH');
	citysForHotel[54]=new Array('QZH','钦州','QINZHOU','QZ');
	citysForHotel[55]=new Array('RKZ','日喀则','RIKAZE','RKZ');
	citysForHotel[56]=new Array('SHS','韶山','SHAOSHAN','SS');
	citysForHotel[57]=new Array('SYM','思茅','SIMAO','SM');
	citysForHotel[58]=new Array('SYX','三亚','SANYA','SY');
	citysForHotel[59]=new Array('TCG','太仓','TAICANG','TC');
	citysForHotel[60]=new Array('TEC','腾冲','TENGCHONG','TC');
	citysForHotel[61]=new Array('TRE','铜仁','TONGREN','TR');
	citysForHotel[62]=new Array('WAN','保亭','BAOTING','BT');
	citysForHotel[63]=new Array('WEC','文昌','WENCHANG','WC');
	citysForHotel[64]=new Array('WUH','武汉','WUHAN','WH');
	citysForHotel[65]=new Array('XGLL','香格里拉','XIANGGELILA','XGLL');
	citysForHotel[66]=new Array('XIC','西昌','XICHANG','XC');
	citysForHotel[67]=new Array('XNG','西宁','XINING','XN');
	citysForHotel[68]=new Array('XYI','兴义','XINGYI','XY');
	citysForHotel[69]=new Array('YAA','雅安','YAAN','YA');
	citysForHotel[70]=new Array('YCN','银川','YINCHUAN','YC');
	citysForHotel[71]=new Array('YIN','伊宁','YINING','YN');
	citysForHotel[72]=new Array('YUL','玉林','YULIN','YL');
	citysForHotel[73]=new Array('YZH','永州','YONGZHOU','YZ');
	citysForHotel[74]=new Array('ZAT','昭通','ZHAOTONG','ZT');
	citysForHotel[75]=new Array('ZHD','中甸','ZHONGDIAN','ZD');
	citysForHotel[76]=new Array('ZHH','珠海','ZHUHAI','ZH');
	citysForHotel[77]=new Array('CAN','广州','GUANGZHOU','GZ');
	citysForHotel[78]=new Array('CHE','潮州','CHAOZHOU','CZ');
	citysForHotel[79]=new Array('EPG','恩平','ENPING','EP');
	citysForHotel[80]=new Array('HEY','河源','HEYUAN','HY');
	citysForHotel[81]=new Array('JIY','揭阳','JIEYANG','JY');
	citysForHotel[82]=new Array('KPG','开平','KAIPING','KP');
	citysForHotel[83]=new Array('MEZ','梅州','MEIZHOU','MZ');
	citysForHotel[84]=new Array('QIN','清远','QINGYUAN','QY');
	citysForHotel[85]=new Array('SHG','韶关','SHAOGUAN','SG');
	citysForHotel[86]=new Array('SHW','汕尾','SHANWEI','SW');
	citysForHotel[87]=new Array('YFU','云浮','YUNFU','YF');
	citysForHotel[88]=new Array('YID','英德','YINGDE','YD');
	citysForHotel[89]=new Array('ZHJ','湛江','ZHANJIANG','ZJ');
	citysForHotel[90]=new Array('FOH','佛山','FOSHAN','FS');
	citysForHotel[91]=new Array('AKA','安康','ANKANG','AK');
	citysForHotel[92]=new Array('ANY','安阳','ANYANG','AY');
	citysForHotel[93]=new Array('ASN','鞍山','ANSHAN','AS');
	citysForHotel[94]=new Array('BEX','本溪','BENXI','BX');
	citysForHotel[95]=new Array('BJI','宝鸡','BAOJI','BJ');
	citysForHotel[96]=new Array('BTO','包头','BAOTOU','BT');
	citysForHotel[97]=new Array('CGO','郑州','ZHENGZHOU','ZZ');
	citysForHotel[98]=new Array('CGQ','长春','CHANGCHUN','CC');
	citysForHotel[99]=new Array('CHG','朝阳','CHAOYANG','CY');
	citysForHotel[100]=new Array('DEZ','德州','DEZHOU','DZ');
	citysForHotel[101]=new Array('DFE','登封','DENGFENG','DF');
	citysForHotel[102]=new Array('DOY','东营','DONGYING','DY');
	citysForHotel[103]=new Array('EDS','鄂尔多斯','EERDUOSI','EEDS');
	citysForHotel[104]=new Array('FSN','抚顺','FUSHUN','FS');
	citysForHotel[105]=new Array('HCG','海城','HAICHENG','HC');
	citysForHotel[106]=new Array('HEB','鹤壁','HEBI','HB');
	citysForHotel[107]=new Array('HEH','黑河','HEIHE','HH');
	citysForHotel[108]=new Array('HES','衡水','HENGSHUI','HS');
	citysForHotel[109]=new Array('HLB','呼伦贝尔','HULUNBEIER','HLBE');
	citysForHotel[110]=new Array('HLH','乌兰浩特','WULANHAOTE','WLHT');
	citysForHotel[111]=new Array('HRB','哈尔滨','HAERBIN','HEB');
	citysForHotel[112]=new Array('JIL','吉林','JILIN','JL');
	citysForHotel[113]=new Array('JIZ','焦作','JIAOZOU','JZ');
	citysForHotel[114]=new Array('JMS','佳木斯','JIAMUSI','JMS');
	citysForHotel[115]=new Array('JOZ','晋中','JINZHONG','JZ');
	citysForHotel[116]=new Array('JZO','胶州','JIAOZHOU','JZ');
	citysForHotel[117]=new Array('KFG','开封','KAIFENG','KF');
	citysForHotel[118]=new Array('LAF','廊坊','LANGFANG','LF');
	citysForHotel[119]=new Array('LIF','临汾','LINFEN','LF');
	citysForHotel[120]=new Array('LIZ','辽阳','LIAOYANG','LY');
	citysForHotel[121]=new Array('LQI','临沂','LINYI','LY');
	citysForHotel[122]=new Array('LUH','漯河','LUOHE','LH');
	citysForHotel[123]=new Array('MDJ','牡丹江','MUDANJIANG','MDJ');
	citysForHotel[124]=new Array('MZL','满洲里','MANZHOULI','MZL');
	citysForHotel[125]=new Array('NAY','南阳','NANYANG','NY');
	citysForHotel[126]=new Array('PEK','北京','BEIJING','BJ');
	citysForHotel[127]=new Array('PJN','盘锦','PANJIN','PJ');
	citysForHotel[128]=new Array('PLI','蓬莱','PENGLAI','PL');
	citysForHotel[129]=new Array('PUY','濮阳','PUYANG','PY');
	citysForHotel[130]=new Array('PYO','平遥','PINGYAO','PY');
	citysForHotel[131]=new Array('QF','曲阜','QUFU','QF');
	citysForHotel[132]=new Array('QHD','秦皇岛','QINHUANGDAO','QHD');
	citysForHotel[133]=new Array('REQ','任丘','RENQIU','RQ');
	citysForHotel[134]=new Array('RZO','日照','RIZHAO','RZ');
	citysForHotel[135]=new Array('SAH','三河','SANHE','SH');
	citysForHotel[136]=new Array('SFH','绥芬河','SUIFENHE','SFH');
	citysForHotel[137]=new Array('SIP','四平','SIPING','SP');
	citysForHotel[138]=new Array('SJW','石家庄','SHIJIAZHUANG','SJZ');
	citysForHotel[139]=new Array('SMU','神木','SHENMU','SM');
	citysForHotel[140]=new Array('SOG','寿光','SHOUGUANG','SG');
	citysForHotel[141]=new Array('SUH','绥化','SUIHUA','SH');
	citysForHotel[142]=new Array('TAN','泰安','TAIAN','TA');
	citysForHotel[143]=new Array('TGO','通辽','TONGLIAO','TL');
	citysForHotel[144]=new Array('TLG','铁岭','TIELING','TL');
	citysForHotel[145]=new Array('TNA','济南','JINAN','JN');
	citysForHotel[146]=new Array('TNH','通化','TONGHUA','TH');
	citysForHotel[147]=new Array('TSN','天津','TIANJIN','TJ');
	citysForHotel[148]=new Array('TYN','太原','TAIYUAN','TY');
	citysForHotel[149]=new Array('WEF','潍坊','WEIFANG','WF');
	citysForHotel[150]=new Array('WQX','汪清县','WANGQINGXIAN','WQX');
	citysForHotel[151]=new Array('WU','五台山','WUTAISHAN','WTS');
	citysForHotel[152]=new Array('XIA','西安','XIAN','XA');
	citysForHotel[153]=new Array('XIL','锡林浩特','XILINHAOTE','XLHT');
	citysForHotel[154]=new Array('XIX','新乡','XINXIANG','XX');
	citysForHotel[155]=new Array('XTA','邢台','XINGTAI','XT');
	citysForHotel[156]=new Array('XUC','许昌','XUCHANG','XC');
	citysForHotel[157]=new Array('XYG','咸阳','XIANYANG','XY');
	citysForHotel[158]=new Array('YAJ','延吉','YANJI','YJ');
	citysForHotel[159]=new Array('YBL','亚布力','YABULI','YBL');
	citysForHotel[160]=new Array('YKU','营口','YINGKOU','YK');
	citysForHotel[161]=new Array('YLN','榆林','YULIN','YL');
	citysForHotel[162]=new Array('YQU','阳泉','YANGQUAN','YQ');
	citysForHotel[163]=new Array('YUC','运城','YUNCHENG','YC');
	citysForHotel[164]=new Array('ZBO','淄博','ZIBO','ZB');
	citysForHotel[165]=new Array('ANJ','安吉','ANJI','AJ');
	citysForHotel[166]=new Array('AQG','安庆','ANQING','AQ');
	citysForHotel[167]=new Array('AXI','安溪','ANXI','AX');
	citysForHotel[168]=new Array('BBU','蚌埠','BANGBU','BB');
	citysForHotel[169]=new Array('CHS','常熟','CHANGSHU','CS');
	citysForHotel[170]=new Array('CIX','慈溪','CIXI','CX');
	citysForHotel[171]=new Array('CLE','长乐','CHANGLE','CL');
	citysForHotel[172]=new Array('COH','巢湖','CHAOHU ','CH');
	citysForHotel[173]=new Array('CZX','常州','CHANGZHOU','CZ');
	citysForHotel[174]=new Array('DAY','丹阳','DANYANG','DY');
	citysForHotel[175]=new Array('DEQ','德清','DEQING','DQ');
	citysForHotel[176]=new Array('DSH','东山','DONGSHAN','DS');
	citysForHotel[177]=new Array('FEH','奉化','FENGHUA','FH');
	citysForHotel[178]=new Array('FOC','福州','FUZHOU','FZ');
	citysForHotel[179]=new Array('FUQ','福清','FUQING','FQ');
	citysForHotel[180]=new Array('FUY','富阳','FUYANG','FY');
	citysForHotel[181]=new Array('FUZ','抚州','FUZHOU','FZ');
	citysForHotel[182]=new Array('HAB','淮北','HUIBEI','HB');
	citysForHotel[183]=new Array('HAN','惠安','HUIAN','HA');
	citysForHotel[184]=new Array('HFE','合肥','HEFEI','HF');
	citysForHotel[185]=new Array('HIA','海安','HAIAN','HA');
	citysForHotel[186]=new Array('HNA','淮南','HUANNAN','HN');
	citysForHotel[187]=new Array('HNB','淮安','HUIAN','HA');
	citysForHotel[188]=new Array('HYN','黄岩','HUANGYAN','HY');
	citysForHotel[189]=new Array('JDE','建德','JIANDE','JD');
	citysForHotel[190]=new Array('JHS','九华山','JIUHUASHAN','JHS');
	citysForHotel[191]=new Array('JID','江都','JIANGDU ','JD');
	citysForHotel[192]=new Array('JIH','金华','JINHUA','JH');
	citysForHotel[193]=new Array('JIX','嘉兴','JIAXING','JX');
	citysForHotel[194]=new Array('JTA','金坛','JINTAN','JT');
	citysForHotel[195]=new Array('JUR','句容','JURONG','JR');
	citysForHotel[196]=new Array('KHN','南昌','NANCHANG','NC');
	citysForHotel[197]=new Array('LXS','兰溪','LANXI','LX');
	citysForHotel[198]=new Array('LEQ','乐清','LEQING','LQ');
	citysForHotel[199]=new Array('LIC','连城','LIANCHENG','LC');
	citysForHotel[200]=new Array('LISH','丽水','LISHUI','LS');
	citysForHotel[201]=new Array('LNY','龙岩','LONGYAN','LY');
	citysForHotel[202]=new Array('LUS','庐山','LUSHAN','LS');
	citysForHotel[203]=new Array('NAN','南安','NANAN','NA');
	citysForHotel[204]=new Array('NAP','南平','NANPING','NP');
	citysForHotel[205]=new Array('NHI','宁海','NINGHAI','NH');
	citysForHotel[206]=new Array('NTG','南通','NANTONG','NT');
	citysForHotel[207]=new Array('PIX','萍乡','PINGXIANG','PX');
	citysForHotel[208]=new Array('PTS','舟山','ZHOUSHAN','ZS');
	citysForHotel[209]=new Array('QGA','泉港','QUANGANG','QG');
	citysForHotel[210]=new Array('QID','启东','QIDONG','QD');
	citysForHotel[211]=new Array('QUZ','衢州','QUZHOU','QZ');
	citysForHotel[212]=new Array('SHA','上海','SHANGHAI','SH');
	citysForHotel[213]=new Array('SHZ','嵊州','SHENGZHOU','SZ');
	citysForHotel[214]=new Array('SIS','石狮','SHISHI','SS');
	citysForHotel[215]=new Array('SMI','三明','SANMING','SM');
	citysForHotel[216]=new Array('SUQ','宿迁','SUQIAN','SQ');
	citysForHotel[217]=new Array('SXG','绍兴','SHAOXING','SX');
	citysForHotel[218]=new Array('TIS','泰顺','TAISHUN','TS');
	citysForHotel[219]=new Array('TIZ','泰州','TAIZHOU','TZ');
	citysForHotel[220]=new Array('TOL','同里','TONGLI','TL');
	citysForHotel[221]=new Array('TOX','桐乡','TONGXIANG','TX');
	citysForHotel[222]=new Array('TZH','台州','TAIZHOU','TZS');
	citysForHotel[223]=new Array('TZS','天柱山','TIANZHUSHAN','TZS');
	citysForHotel[224]=new Array('WHU','芜湖','WUHU','WH');
	citysForHotel[225]=new Array('WUS','武夷山','WUYISHAN','WYS');
	citysForHotel[226]=new Array('WXI','无锡','WUXI','WX');
	citysForHotel[227]=new Array('XCH','新昌','XINCHANG','XC');
	citysForHotel[228]=new Array('XIS','象山','XIANGSHAN','XS');
	citysForHotel[229]=new Array('XMN','厦门','XIAMEN','XM');
	citysForHotel[230]=new Array('XZU','徐州','XUZHOU','XZ');
	citysForHotel[231]=new Array('YDS','雁荡山','YANDANGSHAN','YDS');
	citysForHotel[232]=new Array('YIC','宜春','YICHUN','YC');
	citysForHotel[233]=new Array('YIT','鹰潭','YINGTAN','YT');
	citysForHotel[234]=new Array('YIZ','仪征','YIZHENG','YZ');
	citysForHotel[235]=new Array('YOA','永安','YONGAN','YA');
	citysForHotel[236]=new Array('YOJ','永嘉','YONGJIA','YJ');
	citysForHotel[237]=new Array('ZHA','漳州','ZHANGZHOU','ZZ');
	citysForHotel[238]=new Array('ZJG','张家港','ZHANGJIAGANG','ZJG');
	citysForHotel[239]=new Array('ZJI','镇江','ZHENJIANG','ZJ');
	citysForHotel[240]=new Array('LNJ','临沧','LINCANG','LC');
	citysForHotel[241]=new Array('LPS','六盘水','LIUPANSHUI','LPS');
	citysForHotel[242]=new Array('LUM','芒市','MANGSHI','MS');
	citysForHotel[243]=new Array('LZH','柳州','LIUZHOU','LZ');
	citysForHotel[244]=new Array('MYG','绵阳','MIANYANG','MY');
	citysForHotel[245]=new Array('NNG','南宁','NANNING','NN');
	citysForHotel[246]=new Array('QUJ','曲靖','QUJING','QJ');
	citysForHotel[247]=new Array('SAS','沙市','SHASHI','SS');
	citysForHotel[248]=new Array('SUN','遂宁','SUINING','SN');
	citysForHotel[249]=new Array('SYN','十堰','SHIYAN','SY');
	citysForHotel[250]=new Array('SZX','深圳','SHENZHEN','SZ');
	citysForHotel[251]=new Array('TLF','吐鲁番','TULUFAN','TLF');
	citysForHotel[252]=new Array('URS','乌鲁木齐','WULUMUQI','WLMQ');
	citysForHotel[253]=new Array('WXN','万县','WANXIAN','WX');
	citysForHotel[254]=new Array('XGL','万宁','WANNING','WN');
	citysForHotel[255]=new Array('XIT','湘潭','XIANGTAN','XT');
	citysForHotel[256]=new Array('XXI','湘西','XIANGXI','XX');
	citysForHotel[257]=new Array('YAS','阳朔','YANGSHUO','YS');
	citysForHotel[258]=new Array('YIB','宜宾','YIBIN','YB');
	citysForHotel[259]=new Array('YIY','益阳','YIYANG','YY');
	citysForHotel[260]=new Array('YYA','岳阳','YUEYANG','YY');
	citysForHotel[261]=new Array('ZGG','自贡','ZIGONG','ZG');
	citysForHotel[262]=new Array('ZHY','张掖','ZHANGYE','ZY');
	citysForHotel[263]=new Array('ZZU','株洲','ZHUZHOU','ZZ');
	citysForHotel[264]=new Array('CHY','潮阳','CHAOYANG','CY');
	citysForHotel[265]=new Array('HSO','鹤山','HESHAN','HS');
	citysForHotel[266]=new Array('JMO','江门','JIANGMEN','JM');
	citysForHotel[267]=new Array('MMI','茂名','MAOMING','MM');
	citysForHotel[268]=new Array('SHD','顺德','SHUNDE','SD');
	citysForHotel[269]=new Array('SWA','汕头','SHANTOU','ST');
	citysForHotel[270]=new Array('TSH','台山','TAISHAN','TS');
	citysForHotel[271]=new Array('YJI','阳江','YANGJIANG','YJ');
	citysForHotel[272]=new Array('ZSO','中山','ZHONGSHAN','ZS');
	citysForHotel[273]=new Array('ANT','安图','ANTU','AT');
	citysForHotel[274]=new Array('BDG','保定','BAODING','BD');
	citysForHotel[275]=new Array('BIZ','滨州','BINZHOU','BZ');
	citysForHotel[276]=new Array('BXN','阜新','FUXIN','FX');
	citysForHotel[277]=new Array('CFE','赤峰','CHIFENG','CF');
	citysForHotel[278]=new Array('CHL','昌黎','CHANGLI','CL');
	citysForHotel[279]=new Array('DDG','丹东','DANDONG','DD');
	citysForHotel[280]=new Array('DLC','大连','DALIAN','DL');
	citysForHotel[281]=new Array('DTG','大同','DATONG','DT');
	citysForHotel[282]=new Array('HAZ','汉中','HANZHONG','HZ');
	citysForHotel[283]=new Array('HDN','邯郸','HANDAN','HD');
	citysForHotel[284]=new Array('HEG','鹤岗','HEGANG','HG');
	citysForHotel[285]=new Array('HHHT','呼和浩特','HUHEHAOTE','HHHT');
	citysForHotel[286]=new Array('HLE','海拉尔','HAILAER','HLE');
	citysForHotel[287]=new Array('JIC','晋城','JINCHENG','JC');
	citysForHotel[288]=new Array('JIO','即墨','JIMO','JM');
	citysForHotel[289]=new Array('HED','横店','HENGDIAN','HD');
	citysForHotel[290]=new Array('HGH','杭州','HANGZHOU','HZ');
	citysForHotel[291]=new Array('HIY','海盐','HAIYAN','HY');
	citysForHotel[292]=new Array('HUZ','湖州','HUZHOU','HZ');
	citysForHotel[293]=new Array('JDZ','景德镇','JINGDEZHEN','JDZ');
	citysForHotel[294]=new Array('JIA','吉安','JIAN ','JA');
	citysForHotel[295]=new Array('JIJ','晋江','JINJIANG','JJ');
	citysForHotel[296]=new Array('JJG','九江','JIUJIANG','JJ');
	citysForHotel[297]=new Array('JUY','缙云','JINYUN','JY');
	citysForHotel[298]=new Array('KUS','昆山','KUNSHAN','KS');
	citysForHotel[299]=new Array('LHA','龙海','LONGHAI','LH');
	citysForHotel[300]=new Array('LIHA','临海','LINHAI','LH');
	citysForHotel[301]=new Array('LOY','龙游','LONGYOU','LY');
	citysForHotel[302]=new Array('LYO','溧阳','LIYANG','LY');
	citysForHotel[303]=new Array('NGB','宁波','NINGBO','NB');
	citysForHotel[304]=new Array('NKG','南京','NANJING','NJ');
	citysForHotel[305]=new Array('PIH','平湖','PINGHU','PH');
	citysForHotel[306]=new Array('PUT','莆田','PUTIAN','PT');
	citysForHotel[307]=new Array('QHU','泉州','QUANZHOU','QZ');
	citysForHotel[308]=new Array('RUA','瑞安','RUIAN','RA');
	citysForHotel[309]=new Array('SHY','上虞','SHANGYU','SY');
	citysForHotel[310]=new Array('SIY','泗阳','SIYANG','SY');
	citysForHotel[311]=new Array('SOZ','苏州','SUZHOU','SZ');
	citysForHotel[312]=new Array('TAG','塔城','TACHENG','TC');
	citysForHotel[313]=new Array('TIX','泰兴','TAIXING','TX');
	citysForHotel[314]=new Array('TOU','桐庐','TONGLU','TL');
	citysForHotel[315]=new Array('TXN','黄山','HUANGSHAN','HS');
	citysForHotel[316]=new Array('WNZ','温州','WENZHOU','WZ');
	citysForHotel[317]=new Array('WUY','武义','WUYI','WY');
	citysForHotel[318]=new Array('XIJ','仙居','XIANJU','XJ');
	citysForHotel[319]=new Array('XIY','新余','XINYU','XY');
	citysForHotel[320]=new Array('YGH','扬州','YANGZHOU','YZ');
	citysForHotel[321]=new Array('YIW','义乌','YIWU','YW');
	citysForHotel[322]=new Array('YKN','永康','YONGKANG','YK');
	citysForHotel[323]=new Array('YPI','延平','YANPING','YP');
	citysForHotel[324]=new Array('ZHZ','周庄','ZHOUZHUANG','ZZ');
	citysForHotel[325]=new Array('RHU','仁怀市','HUANREN','HR');
	citysForHotel[326]=new Array('JYU','济源','JIYUAN','JY');
	citysForHotel[327]=new Array('WIY','婺源','WUYUAN','WY');
	citysForHotel[328]=new Array('WLCB','乌兰察布市','WULANCABU','WLCB');
	citysForHotel[329]=new Array('QINZ','青州','QINGZHOU','QZ');
	citysForHotel[330]=new Array('PIND','平度','PINGDU','PD');
	citysForHotel[331]=new Array('LYAN','莱芜','LAIWU','LW');
	citysForHotel[332]=new Array('ALI','阿里','ALI','AL');
	citysForHotel[333]=new Array('CHZ','郴州','CHENZHOU','CZ');
	citysForHotel[334]=new Array('DEY','德阳','DEYANG','DY');
	citysForHotel[335]=new Array('FGC','防城港','FANGCHENGGANG','FCG');
	citysForHotel[336]=new Array('HEZ','贺州','HEZHOU','HZ');
	citysForHotel[337]=new Array('JSH','吉首','JISHOU','JS');
	citysForHotel[338]=new Array('KWL','桂林','GUILIN','GL');
	citysForHotel[339]=new Array('LZ','林芝','LINZHI','LZ');
	citysForHotel[340]=new Array('SOP','松潘','SONGPAN','SP');
	citysForHotel[341]=new Array('WZ','梧州','WUZHOU','WZ');
	citysForHotel[342]=new Array('YIH','宜昌','YICHANG','YC');
	citysForHotel[343]=new Array('ZYI','遵义','ZHUNYI','ZY');
	citysForHotel[344]=new Array('LNS','陵水','LINGSHUI','LS');
	citysForHotel[345]=new Array('HKG','香港','XIANGGANG','XG');
	citysForHotel[346]=new Array('YCH','阳春','YANGCHUN','YC');
	citysForHotel[347]=new Array('LOK','龙口','LONGKOU','LK');
	citysForHotel[348]=new Array('JNS','胶南市','JIAONAN','JN');
	citysForHotel[349]=new Array('HIYA','海阳','HAIYANG','HY');
	citysForHotel[350]=new Array('FIC','肥城','FEICHENG','FC');
	citysForHotel[351]=new Array('ANS','安顺','ANSHUN','AS');
	citysForHotel[352]=new Array('BJE','毕节','BIJIE','BJ');
	citysForHotel[353]=new Array('CMA','澄迈县','CHENGMAIXIAN','CMX');
	citysForHotel[354]=new Array('DAX','达县','DAXIAN','DX');
	citysForHotel[355]=new Array('DLI','大理','DALI ','DL');
	citysForHotel[356]=new Array('DYU','都匀','DUYUN','DY');
	citysForHotel[357]=new Array('FYN','富蕴','FUYUN','FY');
	citysForHotel[358]=new Array('GUG','贵港','GUIGANG','GG');
	citysForHotel[359]=new Array('HGY','衡阳','HENGYANG','HY');
	citysForHotel[360]=new Array('HTN','和田','HETIAN','HT');
	citysForHotel[361]=new Array('JIM','荆门','JINGMEN','JM');
	citysForHotel[362]=new Array('KAL','凯里','KAILI','KL');
	citysForHotel[363]=new Array('KMG','昆明','KUNMING','KM');
	citysForHotel[364]=new Array('LHW','兰州','LANZHOU','LZ');
	citysForHotel[365]=new Array('LUZ','泸州','LUZHOU','LZ');
	citysForHotel[366]=new Array('PZH','攀枝花','PANZHIHUA','PZH');
	citysForHotel[367]=new Array('SYA','邵阳','SHAOLU','SL');
	citysForHotel[368]=new Array('TOS','通什','TONGSHI','TS');
	citysForHotel[369]=new Array('XFG','襄阳','XIANGYANG','XY');
	citysForHotel[370]=new Array('XSBN','西双版纳','XISHUANGBANNA','XSBN');
	citysForHotel[371]=new Array('YUX','玉溪','YUXI','YX');
	citysForHotel[372]=new Array('ZJJ','张家界','ZHANGJIAJIE','ZJJ');
	citysForHotel[373]=new Array('HUI','惠州','HUIZHOU','HZ');
	citysForHotel[374]=new Array('PLN','普宁','PUNING','PN');
	citysForHotel[375]=new Array('SWB','澄海','CHENGHAI','CH');
	citysForHotel[376]=new Array('ZHQ','肇庆','ZHAOQING','ZQ');
	citysForHotel[377]=new Array('BDH','北戴河','BEIDAIHE','BDH');
	citysForHotel[378]=new Array('CDE','承德','CHENGDE','CD');
	citysForHotel[379]=new Array('CIH','长治','CHANGZHI','CZ');
	citysForHotel[380]=new Array('DQG','大庆','DAQING','DQ');
	citysForHotel[381]=new Array('HCN','韩城','HANCHENG','HC');
	citysForHotel[382]=new Array('HLD','葫芦岛','HULUDAO','HLD');
	citysForHotel[383]=new Array('JIN','济宁','JINING','JN');
	citysForHotel[384]=new Array('JZU','锦州','JINZHOU','JZ');
	citysForHotel[385]=new Array('LIY','辽源','LIAOYUAN','LY');
	citysForHotel[386]=new Array('LYA','洛阳','LUOYANG','LY');                             
	citysForHotel[387]=new Array('NDH','南戴河','NANDAIHE','NDH');                             
	citysForHotel[388]=new Array('PSX','平山县','PINGSHANXIAN','PSX');                         
	citysForHotel[389]=new Array('QQHE','齐齐哈尔','QIQIHAER','QQHE');                          
	citysForHotel[390]=new Array('SHE','沈阳','SHENYANG','SY');                             
	citysForHotel[391]=new Array('SMX','三门峡','SANMENXIA','SMX');                            
	citysForHotel[392]=new Array('TAO','青岛','QINGDAO','QD');                             
	citysForHotel[393]=new Array('TNS','唐山','TANGSHAN','TS');                             
	citysForHotel[394]=new Array('WEH','威海','WEIHAI','WH');                             
	citysForHotel[395]=new Array('WUA','乌海','WUHAI','WH');                             
	citysForHotel[396]=new Array('XIZ','忻州','XIZHOOU','XZ');                             
	citysForHotel[397]=new Array('YAN','延安','YANAN','YA');                             
	citysForHotel[398]=new Array('YNT','烟台','YANTAI','YT');                             
	citysForHotel[399]=new Array('ZJK','张家口','ZHANGJIAKOU','ZJK');                          
	citysForHotel[400]=new Array('BUY','阜阳','FUYANG','FY');                             
	citysForHotel[401]=new Array('CZH','滁州','CHUZHOU','CZ');                             
	citysForHotel[402]=new Array('DHU','德化','DEHUA','DH');                             
	citysForHotel[403]=new Array('FUD','福鼎','FUDING','FD');                             
	citysForHotel[404]=new Array('GZU','赣州','GANZHOU','GZ');                             
	citysForHotel[405]=new Array('HIN','海宁','HAINING','HN');                             
	citysForHotel[406]=new Array('JGS','井冈山','JINGGANGSHAN','JGS');                         
	citysForHotel[407]=new Array('JIS','嘉善','JIASHAN','JS');                             
	citysForHotel[408]=new Array('JYN','江阴','JIANGYIN','JY');                             
	citysForHotel[409]=new Array('LIA','临安','LINAN ','LA');                             
	citysForHotel[410]=new Array('LYG','连云港','LIANYUNGANG','LYG');                          
	citysForHotel[411]=new Array('NID','宁德','NINGDE','ND');                             
	citysForHotel[412]=new Array('QDH','千岛湖','QIANDAOHU','QDH');                            
	citysForHotel[413]=new Array('SHN','上饶','SHANGRAO','SR');                             
	citysForHotel[414]=new Array('SNI','寿宁','SHOUNING','SN');                             
	citysForHotel[415]=new Array('TIT','天台','TIANTAI','TT');                             
	citysForHotel[416]=new Array('HZE','菏泽','HEZE','HZ');                             
	citysForHotel[417]=new Array('LAC','聊城','LIAOCHENG','LC');                             
	citysForHotel[418]=new Array('ZOZ','枣庄','ZHAOZHUANG','ZZ');                             
	citysForHotel[419]=new Array('MAS','马鞍山','MAANSHAN ','MAS');                            
	citysForHotel[420]=new Array('TOZ','通州','TONGZHOU','TZ');                             
	citysForHotel[421]=new Array('WUJ','吴江','WUJIANG','WJ');                             
	citysForHotel[422]=new Array('XIQ','新沂','XINYI','XY');                             
	citysForHotel[423]=new Array('YAZ','扬中','YANGZHONG','YZ');                             
	citysForHotel[424]=new Array('YIX','宜兴','YIXING','YX');                             
	citysForHotel[425]=new Array('YUY','余姚','YUYAO','YY');                             
	citysForHotel[426]=new Array('WEL','温岭','WENLING','WL');                             
	citysForHotel[427]=new Array('YAC','盐城','YANCHENG','YC');                             
	citysForHotel[428]=new Array('ZUJ','诸暨','ZHUJI','ZJ');                             
	citysForHotel[429]=new Array('WDS','文登市','WENDENG','WD');                             
	citysForHotel[430]=new Array('PZHO','邳州','PIZHOU','PZ');                             
	citysForHotel[431]=new Array('JINJ','靖江','JINGJIANG','JJ');                             
	citysForHotel[432]=new Array('CBS','长白山','CHANGBAISHAN','CBS');                         
	citysForHotel[433]=new Array('LYN','莱阳市','LAIYANG','LY');                             
	citysForHotel[434]=new Array('WZNX','吴忠','WUZHONG','WZ');                             
	citysForHotel[435]=new Array('GY','固原','GUYUAN','GY');                             
	citysForHotel[436]=new Array('SZS','石嘴山','SHIZUISHAN','SZS');                           
	citysForHotel[437]=new Array('CZ','沧州','CANGZHOU','CZ');                             
	citysForHotel[438]=new Array('RGS','如皋市','RUGAOSHI','RGS');                             
	citysForHotel[439]=new Array('ZYX','资源县','ZIYUANXIAN','ZYX');                           
	citysForHotel[440]=new Array('YZU','兖州','YANZHOU','YZ');                             
	citysForHotel[441]=new Array('LXI','莱西 ','LAIXI','LX');                             
	citysForHotel[442]=new Array('XJN','夏津','XIAJIN','XJ');                             
	citysForHotel[443]=new Array('RONC','荣成','RONGCHENG','RC');                             
	citysForHotel[444]=new Array('WW','武威','WUWEI','WW');                             
	citysForHotel[445]=new Array('ZHW','中卫','ZHONGWEI','ZW');                             
	citysForHotel[446]=new Array('BOX','博兴','BOXING','BX');                             
	citysForHotel[447]=new Array('ZHUC','诸城','ZHUCHENG','ZC');                             
	citysForHotel[448]=new Array('XIM','新密','XINMI','XM');                             
	citysForHotel[449]=new Array('LA','六安','LIUAN','LA');                             
	citysForHotel[450]=new Array('TL','铜陵','TONGLING','TL');                             
	citysForHotel[451]=new Array('XG','孝感','XIAOGAN','XG');                             
	citysForHotel[452]=new Array('JSJYAC','姜堰','JIANGYAN','JY');                             
	citysForHotel[453]=new Array('XICH','兴城','XINGCHENG','XC');  
	citysForHotel[454]=new Array('PUJ','浦江','PUJIANG','PJ');      
	citysForHotel[455]=new Array('QIA','迁安','QIANAN','QA');
	citysForHotel[456]=new Array('SY','松原','SONGYUAN','SY');
	citysForHotel[457]=new Array('HKG','香港','HONGKONG','HK');
    citysForHotel[458]=new Array('ZQS','章丘','ZHANGQIU','ZQ');
    citysForHotel[459]=new Array('MAC','澳门','MACAU','MC');
    citysForHotel[460]=new Array('THAI','唐海','TANGHAI','TH');
    citysForHotel[461]=new Array('LUDG','泸定','LUDING','LD');
	citysForHotel[462]=new Array('MS','眉山','MEISHAN','MS');
	citysForHotel[463]=new Array('SZ','随州','SUIZHOU','SZ');	
	citysForHotel[464]=new Array('CBI','赤壁','CIBI','CB');
	citysForHotel[465]=new Array('DZHI','大治','DAZHI','DZ');
	citysForHotel[466]=new Array('YICH','应城','YINGCHENG','YC');
	citysForHotel[467]=new Array('ZHXI','钟祥','ZHONGXIANG','ZX');
	citysForHotel[468]=new Array('ZIXG','资兴','ZIXING','ZX');
	citysForHotel[469]=new Array('XIAX','湘乡','XIANGXIANG','XX');
	citysForHotel[470]=new Array('LIUY','浏阳','LIUYANG','LY');
	citysForHotel[471]=new Array('PUER','普洱','PUER','PE');
	citysForHotel[472]=new Array('DAX','达州','DAZHOU','DZ');
	citysForHotel[473]=new Array('MEK','马尔康','MAERKANG','MEK');
	citysForHotel[474]=new Array('BCH','北川','BEICHUAN','BC');
	citysForHotel[475]=new Array('LZHG','阆中','LANGZHONG','LZ');
	citysForHotel[476]=new Array('LAIZ','莱州','LAIZHOU','LZ');
	citysForHotel[477]=new Array('XYN','荥阳','XINGYANG','XY');
	citysForHotel[478]=new Array('QXA','栖霞','QIXIA','QX');
    citysForHotel[479]=new Array('DH','德宏傣族景颇族自治州','DEHONGDAIZUJINGPOZUZIZHIZHOU','DHDZJPZZZZ');
	citysForHotel[480]=new Array('NBS','白山','BAISHAN','BS');
	citysForHotel[481]=new Array('TINS','天水','TIANSHUI','TS');
	citysForHotel[482]=new Array('EZ','鄂州','EZHOU','EZ');
	citysForHotel[483]=new Array('HS','黄石','HUANGSHI','HS');
	citysForHotel[484]=new Array('RSS','乳山','RUSHANSHI','RSS');
	citysForHotel[485]=new Array('HLS','海林','HAILIN','HL');
	citysForHotel[486]=new Array('JSJYAC','姜堰','JIANGYAN','JY');
